### ISSUE TITLE
Close serversync in update time

### ISSUE THREAD

**Issue by gollariel** [superzanti/ServerSync#119]
#### Serversync Version: 
2.6.17

#### Minecraft Version: 
1.12.2 (forge 14.23.5.2768)

#### Issue: 
If client closed window in update time, then we can see a lot of errors in the log (on server)

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:79)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.lang.Thread.run(Thread.java:748)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: java.io.EOFException
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:79)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.lang.Thread.run(Thread.java:748)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: java.io.EOFException
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:79)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.lang.Thread.run(Thread.java:748)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: java.io.EOFException
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:79)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.lang.Thread.run(Thread.java:748)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: java.io.EOFException
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:79)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [com.superzanti.serversync.ServerWorker:run:90]: 	at java.lang.Thread.run(Thread.java:748)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.OutOfMemoryError: unable to create new native thread
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.start0(Native Method)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.start(Thread.java:717)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Timer.<init>(Timer.java:176)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Timer.<init>(Timer.java:146)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.superzanti.serversync.ServerWorker.run(ServerWorker.java:77)
[11:28:21] [ClientThread - /46.133.133.86/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)

</pre>
</details>

**Comment by rheimus** [comment]
Indeed, I don't think SS is currently handling the case where a user terminates part way through an update.

Does this actually nuke the server, or is this just console spam with the server still being operable afterward?

**Comment by rheimus** [comment]
Nvm, didn't see the OOM error at the end of the log there.

Definitely not so good.

**Comment by rheimus** [comment]
Could you try using version 2.6.20 of ServerSync.

I am not seeing this issue when closing the client part way through a file download.

**Comment by gollariel** [comment]
It`s just spam logs. I will try the newer version later. Thanks!

**Comment by rheimus** [comment]
Closing, reopen if the problem still persists
