### ISSUE TITLE
Server Crash by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Haocen2004** [superzanti/ServerSync#132]
#### Serversync Version: 
2.6.22  clone from github , no edit
#### Minecraft Version: 
1.12.2
#### Issue: 
Server crashes when ServerSync loads the config folder
Only on linux

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/1/19 10:55 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ServerSync (com.superzanti.serversync)
Caused by: java.lang.NullPointerException
	at com.superzanti.serversync.filemanager.FileManager.getConfigurationFiles(FileManager.java:84)
	at com.superzanti.serversync.server.ServerSetup.<init>(ServerSetup.java:109)
	at runme.Main.runInServerMode(Main.java:92)
	at runme.Main.main(Main.java:44)
	at com.superzanti.serversync.forgeloader.ForgeLoaderNET.startServersync(ForgeLoaderNET.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-18362-Microsoft
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 311977216 bytes (297 MB) / 830472192 bytes (792 MB) up to 1881145344 bytes (1794 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version      | Source                                  | Signature                                |
	|:----- |:------------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                 | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp                       | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML                       | 8.0.99.99    | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                     | 14.23.5.2838 | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCE   | com.superzanti.serversync | 2.6.22       | serversync-2.6.22.jar                   | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
</pre>
</details>

**Comment by rheimus** [comment]
This appears to work as expected in WSL using Ubuntu. Essentially the CWD is something other than the root minecraft folder.

- Which flavor of linux are you using
- Where are you running the server from
- How are you starting the server

**Comment by Rx2TF** [comment]
I'm having the same issue on Ubuntu 18.04 LTS running on a VPS.

[crash-2019-07-22_20.44.24-server.txt](https://github.com/superzanti/ServerSync/files/3417508/crash-2019-07-22_20.44.24-server.txt)
[latest.log](https://github.com/superzanti/ServerSync/files/3417506/latest.log)

**Comment by rheimus** [comment]
Do you have your serversync-server.cfg available?

**Comment by rheimus** [comment]
[serversync-2.6.23-alpha.jar.zip](https://github.com/superzanti/ServerSync/files/3450372/serversync-2.6.23-alpha.jar.zip).
_Always scan files from any source_

I have been moving some of the exception handling around in the file manager, the above version might help with the null pointer during startup. Have you tried running serversync standalone rather than being started by forge?

**Comment by rheimus** [comment]
Closing as I can not reproduce the issue.
