### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#219]
My brain hurts @rheimus 

LOG:Loading language file: en_US
LOG:Starting server in mode: 2
LOG:Starting scan for managed files: Nov 16, 2020
LOG:Ignore patterns: {
  **/serversync-*.jar
  **/serversync-*.cfg
}
DEBUG:root dir: S:\Server\mc-1.16.4-KoolKidsClan-Forge-SS
java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"path":"mods","mode":"mirror"}
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.superzanti.serversync.files.FileManager.getDiffableFilesFromDirectories(FileManager.java:48)
        at com.superzanti.serversync.server.ServerSetup.populateManifest(ServerSetup.java:51)
        at com.superzanti.serversync.server.ServerSetup.<init>(ServerSetup.java:76)
        at com.superzanti.serversync.ServerSync.runInServerMode(ServerSync.java:111)
        at com.superzanti.serversync.ServerSync.call(ServerSync.java:66)
        at com.superzanti.serversync.ServerSync.call(ServerSync.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at com.superzanti.serversync.ServerSync.main(ServerSync.java:56)

**Comment by P3rf3ctXZer0** [comment]
using this serversync-3.7.0-alpha.4-all.jar

and these args.

@echo off
SETLOCAL
SET server_name=1.16.4-KoolKidsClan-Forge-SS
for %%f in (forge*.jar) do (SET forge=%%~nxf)
for %%f in (serversync*.jar) do (SET serversync=%%~nxf)
java %serversync_java_arguments% -jar %serversync% --server
java -Xms2g -Xmx4g -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dfml.queryResult=confirm -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar %forge% nogui
ENDLOCAL
pause

**Comment by P3rf3ctXZer0** [comment]
FIXED

DEFAULT ERRORS OUT

{
  "general": {
    "push_client_mods": false,
    "sync_mode": 2
  },
  "connection": {
    "port": 38067
  },
  "rules": {
    "directory_include_list": [
      "{\"path\":\"mods\",\"mode\":\"mirror\"}"
    ],
    "file_ignore_list": [
      "**/serversync-*.jar",
      "**/serversync-*.cfg"
    ],
    "redirect_files": [
      
    ]
  },
  "misc": {
    "locale": "en_US"
  }
}


but changing it to this

{
  "general": {
    "push_client_mods": false,
    "sync_mode": 2
  },
  "connection": {
    "port": 38067
  },
  "rules": {
    "directory_include_list": [
    "mods"
    ],
    "file_ignore_list": [
      "**/serversync-*.jar",
      "**/serversync-*.cfg"
    ],
    "redirect_files": [
      
    ]
  },
  "misc": {
    "locale": "en_US"
  }
}

makes it work.

**Comment by rheimus** [comment]
Legit bug, the json entry should not be getting generated as a string

**Comment by P3rf3ctXZer0** [comment]
Ah well glad I could help XD

**Comment by P3rf3ctXZer0** [comment]
First day back and I am already useful @rheimus ;P

**Comment by rheimus** [comment]
Indeed
