### ISSUE TITLE
config version error between 4.0.0alpha.1 and 3.7.0-alpha.1.jar

### ISSUE THREAD

**Issue by mindcloud69** [superzanti/ServerSync#230]
And Yes I understand it is alpha and not ready for production I am just trying to help out by testing.
#### Serversync Version: 
4.0.0alpha.1 and 3.7.0-alpha.1.jar
#### Minecraft Version: 
1.16.4
#### Issue: 

In my previous issue I was testing 4.0.0alpha.1 I noticed that when changing from 3.7 to 4.0.0 with the config file changes between them that version 4.0 errors out. On windows with an exe it just never starts and does not throw an error. On Linux it throws the error below. You might want to put in some logic to catch this and throw a friendly error to the user or better yet convert to the new config format.

<details>
<summary>Linux wrong config error</summary>
<pre>
java.lang.NullPointerException
        at com.superzanti.serversync.config.JsonConfig.getArray(JsonConfig.java:260)
        at com.superzanti.serversync.config.JsonConfig.forServer(JsonConfig.java:54)
        at com.superzanti.serversync.config.ConfigLoader.load(ConfigLoader.java:24)
        at com.superzanti.serversync.ServerSync.runInServerMode(ServerSync.java:108)
        at com.superzanti.serversync.ServerSync.call(ServerSync.java:69)
        at com.superzanti.serversync.ServerSync.call(ServerSync.java:27)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at com.superzanti.serversync.ServerSync.main(ServerSync.java:59)

</pre>
</details>

**Comment by rheimus** [comment]
Added handlers for missing entries from 3.7, see v4.0.1
