### ISSUE TITLE
The ServerSyncClient.exe does not show GUI

### ISSUE THREAD

**Issue by Oratorian** [superzanti/ServerSync#280]
Minecraft 1.16.4
ServerSync : 4.2.0

When i click it it just creates the config file, log folder and the log.
After that nothing hapens, no gui no nothing.

**Comment by rheimus** [comment]
Can you add the content of the logfile please.

What java version do you have installed, does it include java FX?

**Comment by Oratorian** [comment]
The Logfile is empty.

And installed java version ist Java8u301 from java.com/download

**Comment by stanlystark** [comment]
java -jar serversync-4.2.0.jar
[рту. 11, 2021 9:01:27][ServerSync] INFO: Root dir: C:\Users\user\curseforge\minecraft\Instances\Client1
[рту. 11, 2021 9:01:27][ServerSync] INFO: Running version: v4.2.0
[рту. 11, 2021 9:01:27][ServerSync] INFO: Loading language file: ru_RU
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.superzanti.serversync.GUIJavaFX.GUI_Launcher.run(GUI_Launcher.java:9)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more

**Comment by rheimus** [comment]
@stanlystark Your java install is missing JavaFX, I am working on a version of serversync that bundles JavaFX so that you don't need to personally install it.

the `-o` flag is running without the interface so JavaFX never gets loaded 😊

@Oratorian 
Interesting, I would expect at very least to see a few lines like the logs posted from @stanlystark about root directory and version, especially if folders are being created when running SS.

Can you please try running this command from your terminal of choice, it might give us some output to help debugging.
```
java -jar serversync-4.2.0.jar
```

**Comment by rheimus** [comment]
Should be fixed by #319
