### ISSUE TITLE
Can't connect to my own server

### ISSUE THREAD

**Issue by yeh111w** [superzanti/ServerSync#317]
#### Issue: 

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

024年2月18日 下午5:13:02
[2月 18, 2024 5:13:02][ServerSync] INFO: Failed to create client streams
[2月 18, 2024 5:13:02][ServerSync] SEVERE: Error in client setup: /127.0.0.1
Exception in thread "ServerSync - Server Client: /127.0.0.1" java.lang.NullPointerException: Cannot invoke "java.io.ObjectInputStream.readUTF()" because "this.ois" is null
        at com.superzanti.serversync.server.ServerWorker.run(ServerWorker.java:90)
        at java.base/java.lang.Thread.run(Thread.java:833)
[2月 18, 2024 5:15:02][ServerSync] INFO: Client connection timed out, closing Socket[addr=/127.0.0.1,port=61141,localport=25525]
</pre>
</details>

**Comment by rheimus** [comment]
The leading slash looks odd? Should not be required for connecting to localhost.
