### ISSUE TITLE
Endless Loading Loop on Closing Connections

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#5]
If the mod cannot connect to a server it says closing connections and just stays that way forever. It says working 99% You cannot do anything till you close and re-open minecraft.

**Comment by superzanti** [comment]
I just fixed this in the most recent version.

**Comment by DPxKnightxZero** [comment]
Did you take down version 2.1? why?

**Comment by superzanti** [comment]
I did not, download the latest version here:
https://github.com/superzanti/ServerSync/blob/master/build/libs/serversync-2.1.jar

Right click 'view raw' and do 'save as'

**Comment by superzanti** [comment]
DPxKnightxZero, I just updated to version 2.2

Please download the latest release.

**Comment by DPxKnightxZero** [comment]
Alright.

**Comment by superzanti** [comment]
DPxKnightZero,
This only understands your .minecraft folder. Everything is referenced from your .minecraft folder. So Lets say that's stored in ```C:\Minecraft\.minecraft```. Then if you wanted to reference a file in ```C:\Minecraft\apples\```, you would have to type ```../apples/```.


Reopened because this is still a bug.

The program is not timing out properly.

**Comment by BakermanLP** [comment]
I have tested out version 2.2 of serversync and got the following error logs on syncing:

Client:
[11:09:14] [Client thread/INFO] [serversync]: Your BUTTON_ID is: 6001
[11:09:14] [Client thread/INFO] [serversync]: Files may be downloaded to this location:
[11:09:14] [Client thread/INFO] [serversync]: /opt/minecraft/instances/TestingOut/minecraft/.
[11:09:14] [Thread-7/INFO] [serversync]: Establishing a socket connection to the server...
[11:09:14] [Thread-7/INFO] [serversync]: Creaing input/output streams...
[11:09:14] [Thread-7/INFO] [serversync]: Our last update was:20150608_000500
[11:09:14] [Thread-7/INFO] [serversync]: The server's last update was:20150608_000800
[11:09:14] [Thread-7/INFO] [serversync]: Sending requests to Socket Server...
[11:09:14] [Thread-7/INFO] [serversync]: Getting the files on the server...
[11:09:14] [Thread-7/INFO] [serversync]: [./mods/serversync-2.2.jar, ./mods/NotEnoughItems-1.7.10-1.0.5.110-universal.jar, ./mods/CodeChickenCore-1.7.10-1.0.7.46-universal.jar, ./mods/ironchest-1.7.10-6.0.62.742-universal.jar, ./mods/fastcraft-1.21.jar, ./mods/MobiusCore-1.2.5_1.7.10.jar, ./mods/Opis-1.2.5_1.7.10.jar, ./config/forge.cfg, ./config/forgeChunkLoading.cfg, ./config/fastcraft.ini, ./config/CodeChickenCore.cfg, ./config/IronChest.cfg, ./config/Opis.cfg, ./config/serversync.cfg]
[11:09:14] [Thread-7/INFO] [serversync]: Getting all of ./mods's folder contents
[11:09:14] [Thread-7/INFO] [serversync]: Getting all of ./mods/1.7.10's folder contents
[11:09:14] [Thread-7/INFO] [serversync]: Getting all of ./config's folder contents
[11:09:14] [Thread-7/INFO] [serversync]: Getting all of ./config/CustomMainMenu's folder contents
[11:09:14] [Thread-7/INFO] [serversync]: Getting all of ./config/NEI's folder contents
[11:09:14] [Thread-7/INFO] [serversync]: Ignoring: [./mods/CustomMainMenu-MC1.7.10-1.5.jar, ./config/CustomMainMenu/mainmenu.json, ./config/forge.cfg, ./config/forgeChunkLoading.cfg, ./config/splash.properties]
[11:09:14] [Thread-7/INFO] [serversync]: We have a match! ./mods/serversync-2.2.jar
[11:09:14] [Thread-7/INFO] [serversync]: We have a match! ./mods/NotEnoughItems-1.7.10-1.0.5.110-universal.jar
[11:09:15] [Thread-7/INFO] [serversync]: We have a match! ./mods/CodeChickenCore-1.7.10-1.0.7.46-universal.jar
[11:09:15] [Thread-7/INFO] [serversync]: ./mods/ironchest-1.7.10-6.0.62.742-universal.jar Does not exist... Updating...
[11:09:15] [Thread-7/INFO] [serversync]: Reinitializing the connection...
[11:09:15] [Thread-7/INFO] [serversync]: Sending requests to Socket Server...
[11:09:15] [Thread-7/INFO] [serversync]: ./mods/fastcraft-1.21.jar Does not exist... Updating...
[11:09:15] [Thread-7/INFO] [serversync]: Reinitializing the connection...
[11:09:15] [Thread-7/INFO] [serversync]: Sending requests to Socket Server...
[11:09:15] [Thread-7/INFO] [serversync]: ./mods/MobiusCore-1.2.5_1.7.10.jar Does not exist... Updating...
[11:09:15] [Thread-7/INFO] [serversync]: Reinitializing the connection...
[11:09:15] [Thread-7/INFO] [serversync]: Sending requests to Socket Server...
[11:09:15] [Thread-7/INFO] [serversync]: ./mods/Opis-1.2.5_1.7.10.jar Does not exist... Updating...
[11:09:15] [Thread-7/INFO] [serversync]: Reinitializing the connection...
[11:09:15] [Thread-7/ERROR] [serversync]: Exception caught! - java.net.SocketException: Connection reset
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.SocketException: Connection reset
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2313)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2326)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.superzanti.serversync.SyncClientConnection.reinitConn(SyncClientConnection.java:270)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.superzanti.serversync.SyncClientConnection.run(SyncClientConnection.java:166)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.superzanti.serversync.SyncClientConnection.run(SyncClientConnection.java:221)
[11:09:15] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)

Server:
[11:09:14] [Thread-7/INFO] [serversync]: Connection established with Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:14] [Thread-11/INFO] [serversync]: Received message: 0ba4439ee9a46d9d9f14c60f88f45f87 from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:14] [Thread-11/INFO] [serversync]: Received message: f8e45531a3ea3d5c1247b004985175a4 from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:14] [Thread-11/INFO] [serversync]: Received message: 226190d94b21d1b0c7b1a42d855e419d from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:14] [Thread-11/INFO] [serversync]: Received message: 226190d94b21d1b0c7b1a42d855e419d from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:14] [Thread-11/INFO] [serversync]: Received message: 226190d94b21d1b0c7b1a42d855e419d from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:15] [Thread-11/INFO] [serversync]: Received message: 3ac340832f29c11538fbe2d6f75e8bcc from connection Socket[addr=/127.0.0.1,port=46986,localport=38067]
[11:09:15] [Thread-11/INFO] [serversync]: Writing file to client...
[11:09:15] [Thread-11/INFO] [serversync]: Connection Socket[addr=/127.0.0.1,port=46986,localport=38067] is closing.
[11:09:15] [Thread-7/INFO] [serversync]: Connection established with Socket[addr=/127.0.0.1,port=46987,localport=38067]
[11:09:15] [Thread-12/INFO] [serversync]: Received message: 3ac340832f29c11538fbe2d6f75e8bcc from connection Socket[addr=/127.0.0.1,port=46987,localport=38067]
[11:09:15] [Thread-12/INFO] [serversync]: Writing file to client...
[11:09:15] [Thread-12/INFO] [serversync]: Connection Socket[addr=/127.0.0.1,port=46987,localport=38067] is closing.
[11:09:15] [Thread-7/INFO] [serversync]: Connection established with Socket[addr=/127.0.0.1,port=46988,localport=38067]
[11:09:15] [Thread-13/INFO] [serversync]: Received message: 3ac340832f29c11538fbe2d6f75e8bcc from connection Socket[addr=/127.0.0.1,port=46988,localport=38067]
[11:09:15] [Thread-13/INFO] [serversync]: Writing file to client...
[11:09:15] [Thread-13/INFO] [serversync]: Connection Socket[addr=/127.0.0.1,port=46988,localport=38067] is closing.
[11:09:15] [Thread-7/INFO] [serversync]: Connection established with Socket[addr=/127.0.0.1,port=46989,localport=38067]
[11:09:15] [Thread-14/INFO] [serversync]: Received message: 3ac340832f29c11538fbe2d6f75e8bcc from connection Socket[addr=/127.0.0.1,port=46989,localport=38067]
[11:09:15] [Thread-14/INFO] [serversync]: Writing file to client...
[11:09:15] [Thread-14/INFO] [serversync]: Connection Socket[addr=/127.0.0.1,port=46989,localport=38067] is closing.
[11:09:15] [Thread-7/INFO] [serversync]: Connection established with Socket[addr=/127.0.0.1,port=46990,localport=38067]
[11:09:15] [Thread-15/INFO] [serversync]: Error occured: java.net.SocketException: Socket is closed

Hope this will help bugfixing.

**Comment by superzanti** [comment]
May I see your serversync.cfg?

**Comment by superzanti** [comment]
I just updated but have not changed the version. I am at work so I cannot do testing at the moment. Would you mind testing the new version for me?

https://github.com/superzanti/ServerSync/blob/master/build/libs/serversync-2.2.jar

I still have it labeled 2.2 but I can assure you things have changed.

Get back to me on weather or not this fixes the issue.
